# Generated by Django 4.2 on 2023-05-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gamemaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_number', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='guessed_number',
            field=models.IntegerField(null=True),
        ),
    ]
