# Generated by Django 4.2.1 on 2023-05-04 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gamemaster_player_guessed_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemaster',
            name='player',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.player'),
        ),
    ]
