# Generated by Django 4.2.1 on 2023-05-05 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_gamemaster_id_alter_player_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='lastname',
        ),
    ]
