# Generated by Django 4.2.1 on 2023-05-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_remove_player_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemaster',
            name='selected_number',
            field=models.IntegerField(null=True),
        ),
    ]
