# Generated by Django 4.2.1 on 2023-05-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_gamemaster_selected_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='attempts',
            field=models.IntegerField(null=True),
        ),
    ]
